### ISSUE TITLE
Certificate issues 

### ISSUE THREAD

**Issue by pythoneer** [rustsim/nalgebra.org#11]
I have certificate issues (website marked as insecure) on https://nalgebra.org/ 

Firefox 62.0 (Linux)
```
nalgebra.org uses an invalid security certificate. The certificate is only valid for the 
following names: ssl3.ovh.net, www.ssl3.ovh.net Error code: 
SSL_ERROR_BAD_CERT_DOMAIN
```

Chromium 69.0.3497.92 (Official Build) Arch Linux (64-bit)

```
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: ssl3.ovh.net

Issuer: COMODO RSA Domain Validation Secure Server CA
```

**Comment by sebcrozet** [comment]
Thank you for mentioning this. I have fixed the SSL configuraiton of nalgebra.org.
